import { QuestionsInfo } from './types';

export const questionsInfo: QuestionsInfo = {
	title: 'Couldn`t find what you were looking for?',
	email: 'faq@creativeai.com',
	questions: [
		{
			question: 'What is Creative.ai?',
			answer: 'Creative.ai is a generative NFT images creator powered by AI in an easy, enjoyable and accessible way.',
		},
		{
			question: 'What is the benefits of using Creative.ai?',
			answer:
				'Generating AI images and converting them to NFT allows the creator to keep the authority of the art created even though the images are generated by AI.',
		},
		{
			question: 'Can I create AI art with free plan?',
			answer:
				'For sure, it is possible to just play around with the generative AI art for free. Better quality and NFTs feature needs at least the standard plan.',
		},
		{
			question: 'Need I a credit card to start?',
			answer: 'No, you only need credit card for subscribing to standard or pro plan.',
		},
	],
};
