import { QuestionsInfo } from './types';

export const questionsInfo: QuestionsInfo = {
	title: 'Couldn`t find what you were lookin for?',
	email: 'faq@creativeai.com',
	questions: [
		{
			question: 'What is Creative.ai?',
			answer: 'Creative.ai is a generative NFT images creator powered by AI in an easy, enjoyable and accessible way.',
		},
		{
			question: 'What is the benefits of using Creative.ai?',
			answer:
				'Generating AI images and converting them to NFT allows the creator to keep the authority of the art created even though the images are generated by AI.',
		},
		{
			question: 'Is it possible to use the app without an account?',
			answer: 'For sure, it is possible to just play around the generative AI art. Creating NFTs feature needs at least the standard plan.',
		},
	],
};
