import ArrowDownIcon from '../../common/icons/ArrowDownIcon';

const Questions = () => {
	return (
		<section className='flex justify-between items-start w-full gap-5 mt-36 px-12 h-[50vh]'>
			<div className='small-intersection-animation flex flex-col items-start justify-between gap-5'>
				<h3 className='text-4xl font-bold'>Frequently asked questions</h3>
				<div className='flex flex-col'>
					<p>Couldn&apos;t find what you were lookin for?</p>
					<p className='text-[var(--contrast)] underline'>faq@creativeai.com</p>
				</div>
			</div>
			<div className='flex flex-col gap-3 w-[40%]'>
				<details
					name='questions'
					className='small-intersection-animation cursor-pointer group w-full'>
					<summary className='flex items-center justify-between text-zinc-100 rounded-xl shadow-md list-none border p-3 bg-gradient-to-tl from-[var(--card-gray)] to-[var(--card-gray-light)] group-hover:from-[var(--contrast)] group-hover:to-[var(--contrast-light)] group-open:from-[var(--contrast)] group-open:to-[var(--contrast-light)] group-open:border-[var(--contrast-light)]'>
						What is Creative.ai?
						<ArrowDownIcon className='w-6 transition-all duration-300 group-open:rotate-180' />
					</summary>
					<p className='p-3 fade-in-animation'>
						Creative.ai is a generative NFT images creator powered by AI in an easy, enjoyable and accessible way.
					</p>
				</details>
				<details
					name='questions'
					className='small-intersection-animation cursor-pointer group w-full'>
					<summary className='flex items-center justify-between text-zinc-100 rounded-xl shadow-md list-none border p-3 bg-gradient-to-tl from-[var(--card-gray)] to-[var(--card-gray-light)] group-hover:from-[var(--contrast)] group-hover:to-[var(--contrast-light)] group-open:from-[var(--contrast)] group-open:to-[var(--contrast-light)] group-open:border-[var(--contrast-light)]'>
						What is the benefits of using Creative.ai?
						<ArrowDownIcon className='w-6 transition-all duration-300 group-open:rotate-180' />
					</summary>
					<p className='p-3'>
						Generating AI images and converting them to NFT allows the creator to keep the authority of the art created even though the
						images are generated by AI.
					</p>
				</details>
				<details
					name='questions'
					className='small-intersection-animation cursor-pointer group w-full'>
					<summary className='flex items-center justify-between text-zinc-100 rounded-xl shadow-md list-none border p-3 bg-gradient-to-tl from-[var(--card-gray)] to-[var(--card-gray-light)] group-hover:from-[var(--contrast)] group-hover:to-[var(--contrast-light)] group-open:from-[var(--contrast)] group-open:to-[var(--contrast-light)] group-open:border-[var(--contrast-light)]'>
						Is it possible to use the app without an account?
						<ArrowDownIcon className='w-6 transition-all duration-300 group-open:rotate-180' />
					</summary>
					<p className='p-3 fade-in-animation'>
						For sure, it is possible to just play around the generative AI art. Creating NFTs feature needs at least the standard plan.
					</p>
				</details>
			</div>
		</section>
	);
};

export default Questions;
